server:
  port: ${SERVER_PORT:6001}

security:
  jwt:
    public-key: classpath:jwt-signing-public-key.txt

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  zipkin:
    base-url: http://${ZIPKIN_HOST:localhost:9411}
    enabled: true
    service:
      name: bookstore-catalog-service
    message-timeout: 10
  sleuth:
    sampler:
      probability: 1.0
  flyway:
    table: catalog_service_flyway_history
    baseline-on-migrate: true
    baseline-version: 0.9
  main:
    allow-bean-definition-overriding: true
  hateoas:
    use-hal-as-default-json-media-type: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    com.devd.spring.*: DEBUG

---

spring:
  profiles: local
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: h2
    open-in-view: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:bookstore_db;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console

---

spring:
  profiles: mysql
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    open-in-view: true
    generate-ddl: true
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bookstore_db?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: bookstoreDBA
    password: PaSSworD

---

spring:
  profiles: docker
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    open-in-view: true
    generate-ddl: true
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://bookstore-mysql-db:3306/bookstore_db?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: bookstoreDBA
    password: PaSSworD