server:
  port: ${SERVER_PORT:8765}

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  zipkin:
    base-url: http://${ZIPKIN_HOST:localhost:9411}
    enabled: true
    service:
      name: bookstore-api-gateway-service
    message-timeout: 10
  sleuth:
    sampler:
      probability: 1.0
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

zuul:
  sensitiveHeaders:
  host:
    socket-timeout-millis: 30000
    connect-timeout-millis: 30000
  prefix: /api
  routes:
    billing:
      path: /billing/**
      serviceId: bookstore-billing-service
    catalog:
      path: /catalog/**
      serviceId: bookstore-catalog-service
    account:
      path: /account/**
      serviceId: bookstore-account-service
    order:
      path: /order/**
      serviceId: bookstore-order-service
    payment:
      path: /payment/**
      serviceId: bookstore-payment-service
  ribbon:
    eager-load:
      enabled: true
  ribbon-isolation-strategy: THREAD

ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 60000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 40000
